name: terraform-ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ci:
    uses: SPHTech-Platform/reusable-workflows/.github/workflows/terraform.yaml@tflint-version
    with:
      upload_sarif: false
    secrets: inherit
permissions:
  actions: read
  checks: read
  contents: read
  pull-requests: write
  security-events: write
